language: cpp

compiler:
# gcc test is disabled (see #120)
#  - gcc
  - clang

before_install:
  - lsb_release -a
  - uname -a
  - sudo apt-get -qq update

install:
  # msgpack
  - sudo apt-get -qq install libmsgpack-dev
  # oniguruma
  - wget http://www.geocities.jp/kosako3/oniguruma/archive/onig-5.9.4.tar.gz && tar xvf onig-5.9.4.tar.gz
  - pushd onig-5.9.4 && ./configure && make && sudo make install && popd
  - sudo ldconfig

script:
  - ./waf configure
  - ./waf build --checkall

branches:
  only:
    - master
    - develop

notifications:
  email: false
