def options(ctx): pass

def configure(ctx): pass

def build(bld):
  source = [
      'lin_ucb.cpp',
      'arm.cpp',
      'arm_storage.cpp'
      ]
  headers = [
      'lin_ucb.hpp',
      'arm.hpp',
      'arm_storage.hpp',
      'contextual_bandit.hpp'
      ]
  tests = [
  ]
  use = ['jubatus_util']

  bld.core_sources.extend(bld.add_prefix(source))
  bld.core_headers.extend(bld.add_prefix(headers))
  bld.core_use.extend(use)

  for test in tests:
    bld.program(
      features = 'gtest',
      source = test,
      target = test[0:test.rfind('.')],
      includes = '.',
      use = use + ['jubatus_core'])
